---
version: '3'

services:
    docker-registry:
        image: registry:2
        container_name: docker-registry
        ports:
            - 5000:5000
        restart: always
        volumes:
            - /home/appdir/docker/registry/volume:/var/lib/registry
        deploy:
            placement:
                constraints:
                    - node.hostname==h2448355.stratoserver.net

    docker-registry-ui:
        image: konradkleine/docker-registry-frontend:v2
        container_name: docker-registry-ui
        ports:
            - 5001:80
        environment:
            ENV_DOCKER_REGISTRY_HOST: docker-registry
            ENV_DOCKER_REGISTRY_PORT: 5000
        deploy:
            placement:
                constraints:
                    - node.hostname==h2448355.stratoserver.net
